[package]
name = "libnyx_config"
version = "0.1.0"
authors = ["coco <cornelius@hexgolems.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde ="1.0.104"
serde_derive ="1.0.104"
ron="0.6.2"
libc = "0.2"